import { createRequire } from "node:module";
import type { VisualCandidateC2pa } from "@factory/contracts";

/**
 * C2PA READ/VALIDATE/RECORD (Run 7) — thin wrapper over the maintained
 * `@contentauth/c2pa-node` production package. Scope is strictly READ:
 * Run 7 never signs manifests. The result is honest evidence only:
 * - validated: a manifest was present and parsed (bounded summary recorded);
 * - absent: no manifest embedded (the common case for AI-generated bytes);
 * - unreadable: manifest-like content present but parsing failed;
 * - unavailable_with_reason: the C2PA runtime itself could not run.
 * Nothing is ever fabricated as "validated" without a real parse.
 */

const require = createRequire(import.meta.url);

export async function readC2paEvidence(input: {
  bytes: Uint8Array;
  mediaType: string;
}): Promise<VisualCandidateC2pa> {
  let c2paModule: unknown;
  try {
    // Lazy require so a broken native binary degrades to typed evidence
    // instead of crashing the ingest path.
    c2paModule = require("@contentauth/c2pa-node");
  } catch (error) {
    return {
      status: "unavailable_with_reason",
      reason: `C2PA runtime unavailable: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
  try {
    const mod = c2paModule as { Reader: { fromAsset(asset: { buffer: Buffer; mimeType: string }): Promise<unknown> } };
    const reader = await mod.Reader.fromAsset({
      buffer: Buffer.from(input.bytes),
      mimeType: input.mediaType,
    });
    if (reader === null || reader === undefined) {
      return { status: "absent" };
    }
    const json = (reader as { json(): unknown }).json();
    const manifest = extractActiveManifest(json);
    if (!manifest) {
      return { status: "absent" };
    }
    const generator =
      typeof manifest["claim_generator"] === "string" ? manifest["claim_generator"] : undefined;
    const signatureInfo = manifest["signature_info"] as Record<string, unknown> | undefined;
    return {
      status: "validated",
      manifestSummary: {
        generator: generator?.slice(0, 200),
        signed: signatureInfo != null,
      },
    };
  } catch (error) {
    return {
      status: "unreadable",
      reason: `C2PA manifest parse failed: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

function extractActiveManifest(manifestStore: unknown): Record<string, unknown> | null {
  if (manifestStore == null || typeof manifestStore !== "object") return null;
  const store = manifestStore as Record<string, unknown>;
  const active = store["active_manifest"];
  if (typeof active === "string") {
    const manifests = store["manifests"] as Record<string, unknown> | undefined;
    const candidate = manifests?.[active];
    return candidate != null && typeof candidate === "object" ? (candidate as Record<string, unknown>) : null;
  }
  if (active != null && typeof active === "object") return active as Record<string, unknown>;
  return null;
}
