import { createRequire } from "node:module";
import type { VisualCandidateC2pa } from "@factory/contracts";

/**
 * C2PA READ/VALIDATE/RECORD (Run 7) — thin wrapper over the maintained
 * `@contentauth/c2pa-node` production package. Scope is strictly READ:
 * Run 7 never signs manifests. The result is honest evidence only:
 * - validated: a manifest was present and parsed (bounded summary recorded);
 * - absent: no manifest embedded (the common case for AI-generated bytes);
 * - unreadable: manifest-like content present but parsing failed;
 * - unavailable_with_reason: the C2PA runtime itself could not run.
 * Nothing is ever fabricated as "validated" without a real parse.
 */

const require = createRequire(import.meta.url);

export async function readC2paEvidence(input: {
  bytes: Uint8Array;
  mediaType: string;
}): Promise<VisualCandidateC2pa> {
  let c2paModule: unknown;
  try {
    // Lazy require so a broken native binary degrades to typed evidence
    // instead of crashing the ingest path.
    c2paModule = require("@contentauth/c2pa-node");
  } catch (error) {
    return {
      status: "verification_unavailable",
      reason: `C2PA runtime unavailable: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
  try {
    const mod = c2paModule as {
      Reader: {
        fromAsset(
          asset: { buffer: Buffer; mimeType: string },
          settings?: unknown,
        ): Promise<unknown>;
      };
    };
    // SSRF & egress protection (P1-11): disable remote manifest fetching
    // and OCSP network calls on untrusted provider bytes.
    const readerSettings = {
      verify: {
        verify_after_reading: true,
        verify_trust: false,
        remote_manifest_fetch: false,
        ocsp_fetch: false,
      },
    };
    const reader = await mod.Reader.fromAsset(
      {
        buffer: Buffer.from(input.bytes),
        mimeType: input.mediaType,
      },
      readerSettings,
    );
    if (reader === null || reader === undefined) {
      return { status: "absent" };
    }
    const json = (reader as { json(): Record<string, unknown> }).json();
    const manifest = extractActiveManifest(json);
    if (!manifest) {
      return { status: "absent" };
    }

    const generator =
      typeof manifest["claim_generator"] === "string" ? manifest["claim_generator"] : undefined;
    const signatureInfo = manifest["signature_info"] as Record<string, unknown> | undefined;

    // Detailed validation status classification (P1-10)
    const rawValidationStatus = json["validation_status"];
    const validationList = Array.isArray(rawValidationStatus) ? rawValidationStatus : [];
    const validationCodes: string[] = validationList
      .map((item) => (typeof item === "string" ? item : (item as { code?: string })?.code))
      .filter((code): code is string => typeof code === "string");

    let status: VisualCandidateC2pa["status"] = "present_valid";
    if (validationCodes.length > 0) {
      const hasCorruptionOrMismatch = validationCodes.some((code) =>
        code.includes("mismatch") ||
        code.includes("corrupt") ||
        code.startsWith("assertion.") ||
        code.startsWith("claimSignature.")
      );
      if (hasCorruptionOrMismatch) {
        status = "present_invalid";
      } else if (validationCodes.every((code) => code.includes("untrusted"))) {
        status = "present_untrusted";
      } else {
        status = "present_invalid";
      }
    }

    return {
      status,
      manifestSummary: {
        generator: generator?.slice(0, 200),
        signed: signatureInfo != null,
        validationCodes: validationCodes.slice(0, 10),
      },
    };
  } catch (error) {
    return {
      status: "unreadable",
      reason: `C2PA manifest parse failed: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

function extractActiveManifest(manifestStore: unknown): Record<string, unknown> | null {
  if (manifestStore == null || typeof manifestStore !== "object") return null;
  const store = manifestStore as Record<string, unknown>;
  const active = store["active_manifest"];
  if (typeof active === "string") {
    const manifests = store["manifests"] as Record<string, unknown> | undefined;
    const candidate = manifests?.[active];
    return candidate != null && typeof candidate === "object" ? (candidate as Record<string, unknown>) : null;
  }
  if (active != null && typeof active === "object") return active as Record<string, unknown>;
  return null;
}
